import { CreateStartUpPageContainer, EventSourceType, OsEventTypeList, TextContainerProperty, TextContainerUpgrade, waitForEvenAppBridge } from '@evenrealities/even_hub_sdk'
import { decideCodingApproval, initializePersistentStorage, isPaired, loadCachedSummary, loadSummary, type HudSummary, type NflHudCategory } from './api'
import { mountPhoneControls } from './phone'

type View='menu'|'detail'
type SectionId='daily'|'builder'|'legal'|'coding'|'gtd'|'eventEdge'|'system'
const sections:Array<{id:SectionId;name:string}>=[{id:'daily',name:'Daily Command'},{id:'builder',name:'Builder OS'},{id:'legal',name:'Legal OS'},{id:'coding',name:'Coding Approvals'},{id:'gtd',name:'GTD NFL Picks'},{id:'eventEdge',name:'Event Edge'},{id:'system',name:'System Status'}]
let selectedIndex=0,itemIndex=0
let currentView:View='menu'
let summary:HudSummary|null=null
let connectionState='Starting',lastInput='Ready',longPressStartedAt=0
const bridge=await waitForEvenAppBridge()
await initializePersistentStorage(bridge)
summary=loadCachedSummary();connectionState=isPaired()?'Cached':'Pair on phone'
mountPhoneControls(()=>{void refreshData()})
const clean=(value:string|null|undefined,max=120)=>(value??'None').replace(/\s+/g,' ').trim().slice(0,max)
const currentSection=()=>sections[selectedIndex]
const nflCategories=():NflHudCategory[]=>summary?.gtd.nflOwnerBrief?.categories??[]
const pct=(value:number|null)=>value==null?'--':`${Math.round(value*100)}%`
const sectionStatus=(id:SectionId)=>{if(!summary)return id==='system'?connectionState:'Awaiting connection';switch(id){case'daily':return`C${summary.counts.codingApprovals} L${summary.counts.legalApprovals} B${summary.counts.builderProposals}`;case'builder':return`${summary.counts.builderProposals} proposals`;case'legal':return`${summary.counts.legalApprovals} awaiting review`;case'coding':return`${summary.counts.codingApprovals} awaiting decision`;case'system':return`${summary.system.status} · ${connectionState}`;case'gtd':{const brief=summary.gtd.nflOwnerBrief;return brief?`${brief.categories.length} NFL categories · ${brief.gameDate}`:'No NFL briefing'}case'eventEdge':return`${summary.eventEdge.sourceStatus} · ${summary.eventEdge.activeSignals} signals`}}
const renderMenu=()=>['CITADEL COMMAND','----------------',...sections.map((s,i)=>`${i===selectedIndex?'>':' '} ${s.name}  ${sectionStatus(s.id)}`),'',`${lastInput} | tap=open`].join('\n')
const selectedCodingApproval=()=>summary?.codingApprovals[itemIndex]??null
const renderGtd=()=>{const brief=summary?.gtd.nflOwnerBrief;if(!brief)return['GTD NFL PICKS','----------------','No Owners Brief snapshot.','','The board appears after the briefing email is accepted and published.','','Long press: refresh','Double press: back'].join('\n');const groups=nflCategories();const group=groups[itemIndex];if(!group)return['GTD NFL PICKS','----------------','No categories in current briefing.','','Long press: refresh','Double press: back'].join('\n');return[`NFL ${itemIndex+1}/${groups.length} · ${brief.gameDate}`,'----------------',clean(group.label,54),...group.picks.slice(0,5).map(p=>`${p.rank}. ${clean(p.player,22)} ${p.direction??''} ${p.line??'--'} ${pct(p.modelProbability)}`),'',`${brief.calibrationStatus} · ${brief.briefingDate}`,'Swipe: category · Hold: refresh'].join('\n')}
const renderDetail=()=>{const s=currentSection();if(!summary)return['CITADEL COMMAND','----------------','NOT CONNECTED','','Open Citadel Command on phone.','Enter the Command Center pairing code.','','Long press: refresh','Double press: back'].join('\n');if(s.id==='gtd')return renderGtd();if(s.id==='coding'){const a=selectedCodingApproval();return a?[`CODING ${itemIndex+1}/${summary.codingApprovals.length}`,'----------------',clean(a.title,60),`${a.source} · ${a.risk.toUpperCase()}`,'',clean(a.action,115),'',a.risk==='high'||a.risk==='critical'?'DESKTOP CONFIRMATION REQUIRED':'Hold 1.5 sec to APPROVE','Double press: back'].join('\n'):['CODING APPROVALS','----------------','No pending requests.','','Long press: refresh','Double press: back'].join('\n')}if(s.id==='legal'){const p=summary.legalApprovals[itemIndex];return p?[`LEGAL REQUEST ${itemIndex+1}/${summary.legalApprovals.length}`,'----------------',`Matter: ${clean(p.matterId,50)}`,`Risks: ${clean(p.riskFlags?.join(', ')||'none',90)}`,'',clean(p.proposedExternalAction||'Internal review packet',130),'','Review/decision on phone or desktop','Double press: back'].join('\n'):['LEGAL AGENT OS','----------------','No pending review packets.','','Long press: refresh','Double press: back'].join('\n')}if(s.id==='builder'){const p=summary.builderProposals[itemIndex],r=summary.recentSessions.find(x=>/builder|platform/i.test(x.project+x.title));return p?[`BUILDER ${itemIndex+1}/${summary.builderProposals.length}`,'----------------',clean(p.project,50),'',clean(p.text,190),'','Proposal awaiting operator promotion','Double press: back'].join('\n'):['BUILDER OS','----------------',clean(r?.status||'No proposed work',60),'',clean(r?.nextStart||r?.summary||'No current update.',210),'','Long press: refresh','Double press: back'].join('\n')}if(s.id==='daily')return['DAILY COMMAND','----------------',`Coding approvals: ${summary.counts.codingApprovals}`,`Legal reviews: ${summary.counts.legalApprovals}`,`Builder proposals: ${summary.counts.builderProposals}`,`NFL categories: ${nflCategories().length}`,`System: ${summary.system.status}`,'',`Updated: ${new Date(summary.updatedAt).toLocaleTimeString()}`,'Long press: refresh','Double press: back'].join('\n');if(s.id==='eventEdge'){const e=summary.eventEdge;return['EVENT EDGE','----------------',`${e.sourceStatus.toUpperCase()} · ${e.mode.toUpperCase()} · ${e.paperOnly?'PAPER':'LIVE'}`,`Heartbeat: ${e.heartbeatStatus}`,`Signals: ${e.activeSignals}  Pending: ${e.pendingTrades}`,`Settled: ${e.settled}  Win: ${(e.winRate*100).toFixed(1)}%`,`Net: ${e.normalizedNet>=0?'+':''}${e.normalizedNet.toFixed(2)}`,'',clean(e.detail||e.summary,165),'','Long press: refresh','Double press: back'].join('\n')}return[s.name.toUpperCase(),'----------------',sectionStatus(s.id),'',s.id==='system'?`Faults: ${summary.system.faults}\nLatency: ${summary.system.latencyMs}ms`:'No current update.','','Long press: refresh','Double press: back'].join('\n')}
const render=()=>bridge.textContainerUpgrade(new TextContainerUpgrade({containerID:1,containerName:'citadel-root',content:currentView==='menu'?renderMenu():renderDetail()}))
async function refreshData(){if(!isPaired()){connectionState='Pair on phone';void render();return}connectionState='Refreshing';void render();try{summary=await loadSummary();connectionState='Live';itemIndex=0}catch(error){connectionState=error instanceof Error?clean(error.message,30):'Offline cache'}void render()}
const moveSelection=(delta:number)=>{if(currentView==='menu'){selectedIndex=(selectedIndex+delta+sections.length)%sections.length;itemIndex=0;return}const id=currentSection().id;const count=id==='coding'?summary?.codingApprovals.length??0:id==='legal'?summary?.legalApprovals.length??0:id==='builder'?summary?.builderProposals.length??0:id==='gtd'?nflCategories().length:0;if(count)itemIndex=(itemIndex+delta+count)%count}
const sourceLabel=(source?:EventSourceType)=>source===EventSourceType.TOUCH_EVENT_FROM_RING?'R1':source===EventSourceType.TOUCH_EVENT_FROM_GLASSES_L?'G2 left':source===EventSourceType.TOUCH_EVENT_FROM_GLASSES_R?'G2 right':'G2/sim'
const initialPage=new TextContainerProperty({xPosition:0,yPosition:0,width:576,height:288,borderWidth:0,borderColor:5,paddingLength:4,containerID:1,containerName:'citadel-root',content:renderMenu(),isEventCapture:1})
const result=await bridge.createStartUpPageContainer(new CreateStartUpPageContainer({containerTotalNum:1,textObject:[initialPage]}));if(result!==0)console.error('[citadel] startup failed:',result)
bridge.onEvenHubEvent(event=>{const sys=event.sysEvent,input=event.textEvent??event.listEvent??sys;if(!input)return;lastInput=sourceLabel(sys?.eventSource);if(sys?.eventType===OsEventTypeList.LONG_PRESS_EVENT){longPressStartedAt=Date.now();lastInput=currentView==='detail'&&currentSection().id==='coding'?'Hold to approve…':'Refreshing…';void render();return}if(sys?.eventType===OsEventTypeList.LONG_PRESS_RELEASE_EVENT){const duration=longPressStartedAt?Date.now()-longPressStartedAt:0;longPressStartedAt=0;const approval=currentView==='detail'&&currentSection().id==='coding'?selectedCodingApproval():null;if(approval&&duration>=1500&&!['high','critical'].includes(approval.risk)){lastInput='Submitting approval…';void render();void decideCodingApproval(approval.id,'approve').then(()=>refreshData()).catch(error=>{lastInput=error instanceof Error?clean(error.message,40):'Approval failed';void render()})}else if(!approval)void refreshData();else{lastInput=duration<1500?'Hold longer to approve':'Use desktop for high risk';void render()}return}switch(input.eventType){case OsEventTypeList.SCROLL_TOP_EVENT:moveSelection(-1);break;case OsEventTypeList.SCROLL_BOTTOM_EVENT:moveSelection(1);break;case OsEventTypeList.CLICK_EVENT:case undefined:currentView='detail';break;case OsEventTypeList.DOUBLE_CLICK_EVENT:if(currentView==='detail')currentView='menu';else{void bridge.shutDownPageContainer(1);return}break}void render()})
void refreshData()
